// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duwczapcewamlfkrjstu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1d2N6YXBjZXdhbWxma3Jqc3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDA3ODEsImV4cCI6MjA2ODU3Njc4MX0.W4xikq5zYHy0Leqhu5QmQ3ytqMP0aqFVLDvlzblCNSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});